name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Gitea Container Registry
        run: |
          echo "${{ secrets.RUNNER_TOKEN }}" | docker login git.klsh.ru \
            -u team4 --password-stdin

      - name: Build and push Monolith
        run: |
          docker build -t git.klsh.ru/team4/library:latest .
          docker push git.klsh.ru/team4/library:latest

      - name: Build and push Recommendations Service
        run: |
          docker build -t git.klsh.ru/team4/recommendations:latest ./recomendations-service
          docker push git.klsh.ru/team4/recommendations:latest

      - name: Build and push Reviews Service
        run: |
          docker build -t git.klsh.ru/team4/reviews:latest ./reviews-services
          docker push git.klsh.ru/team4/reviews:latest

      - name: Build and push Notifications Service
        run: |
          docker build -t git.klsh.ru/team4/notifications:latest ./notifications-service
          docker push git.klsh.ru/team4/notifications:latest

      - name: Images pushed successfully
        run: echo "All images pushed successfully"